[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 2
y = 2

[general]
import = ["~/.config/alacritty/ayu_dark.toml"]

[terminal]
shell = "zsh"
